# apt-key
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/apt-key.8.gz
complete -c apt-key -l keyring -d 'With this option it is possible to specify a particular keyring file the comm…'

