# arp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/arp.8.gz
complete -c arp -s v -l verbose -d 'Tell the user what is going on by being verbose'
complete -c arp -s n -l numeric -d 'shows numerical addresses instead of trying to determine symbolic host, port …'
complete -c arp -s H -l hw-type -s t -d 'When setting or reading the ARP cache, this optional parameter tells  arp whi…'
complete -c arp -s a -d 'Use alternate BSD style output format (with no fixed columns)'
complete -c arp -s e -d 'Use default Linux style output format (with fixed columns)'
complete -c arp -s D -l use-device -d 'Instead of a hw_addr, the given argument is the name of an interface'
complete -c arp -s i -l device -d 'Select an interface'
complete -c arp -s f -l file -d 'Similar to the'
complete -c arp -s s -d 'option, only this time the address info is taken from file filename '

