# coreutils
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/coreutils.1.gz
complete -c coreutils -l help -d 'display this help and exit'
complete -c coreutils -l version -d 'output version information and exit'

