# demandoc
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/demandoc.1.gz
complete -c demandoc -s w -d 'Output a word list.  This outputs each word of text on its own line'

