# dnsdomainname
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/dnsdomainname.1.gz
complete -c dnsdomainname -s '?' -l help -d 'give this help list'
complete -c dnsdomainname -l usage -d 'give a short usage message'
complete -c dnsdomainname -s V -l version -d 'print program version AUTHOR Written by Simon Josefsson'

