# expr
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/expr.1.gz
complete -c expr -l help -d 'display this help and exit'
complete -c expr -l version -d 'output version information and exit '

