# factor
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/factor.1.gz
complete -c factor -l help -d 'display this help and exit'
complete -c factor -l version -d 'output version information and exit AUTHOR Written by Paul Rubin, Torbjorn Gr…'

