# freetype-config
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/freetype-config.1.gz
complete -c freetype-config -l prefix -d 'Return the prefix value of the installed FreeType library (the default prefix…'
complete -c freetype-config -l exec-prefix -d 'Return the executable prefix value of the installed FreeType library (will of…'
complete -c freetype-config -l ftversion -d 'Return the FreeType version number, directly derived from file `freetype. h\''
complete -c freetype-config -l version -d 'Return the `libtool version\' of the FreeType library'
complete -c freetype-config -l libtool -d 'Return the library name for linking with libtool'
complete -c freetype-config -l libs -d 'Return compiler flags for linking with the installed FreeType library'
complete -c freetype-config -l cflags -d 'Return compiler flags for compiling against the installed FreeType library'
complete -c freetype-config -l static -d 'Make command line options display flags for static linking'
complete -c freetype-config -l help -d 'Show help and exit. SS Path override options '

