# fsck
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/fsck.minix.8.gz
complete -c fsck -s l -l list
complete -c fsck -s r -l repair
complete -c fsck -l auto
complete -c fsck -s s -l super
complete -c fsck -s m -l uncleared
complete -c fsck -s f -l force

