# ftp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/ftp.1.gz
complete -c ftp -s 4 -l ipv4 -d 'contact IPv4 hosts'
complete -c ftp -s 6 -l ipv6 -d 'contact IPv6 hosts'
complete -c ftp -s A -l active -d 'enable active mode transfer'
complete -c ftp -s d -l debug -d 'enable debugging output'
complete -c ftp -s e -l no-edit -d 'disable command line editing'
complete -c ftp -s g -l no-glob -d 'turn off file name globbing'
complete -c ftp -s i -l no-prompt -d 'do not prompt during multiple file transfers'
complete -c ftp -s n -l no-login -d 'do not automatically login to the remote system'
complete -c ftp -s N -l netrc -d 'select a specific initialization file'
complete -c ftp -s p -l passive -d 'enable passive mode transfer, default for `pftp\''
complete -c ftp -l prompt -d 'print a command line PROMPT (optionally), even if not on a tty'
complete -c ftp -s t -l trace -d 'enable packet tracing'
complete -c ftp -s v -l verbose -d 'verbose output'
complete -c ftp -s '?' -l help -d 'give this help list'
complete -c ftp -l usage -d 'give a short usage message'
complete -c ftp -s V -l version -d 'print program version'

