# ftpd
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/ftpd.8.gz
complete -c ftpd -s 4 -l ipv4 -d 'restrict daemon to IPv4'
complete -c ftpd -s 6 -l ipv6 -d 'restrict daemon to IPv6'
complete -c ftpd -s a -l auth -d 'use AUTH for authentication'
complete -c ftpd -s A -l anonymous-only -d 'server configured for anonymous service only'
complete -c ftpd -s d -l debug -d 'debug mode'
complete -c ftpd -s D -l daemon -d 'start the ftpd standalone'
complete -c ftpd -s l -l logging -d 'increase verbosity of syslog messages'
complete -c ftpd -l non-rfc2577 -d 'neglect RFC 2577 by giving info on missing users'
complete -c ftpd -s p -l pidfile -d 'change default location of pidfile'
complete -c ftpd -s q -l no-version -d 'do not display version in banner'
complete -c ftpd -s t -l timeout -d 'set default idle timeout'
complete -c ftpd -s T -l max-timeout -d 'reset maximum value of timeout allowed'
complete -c ftpd -s u -l umask -d 'set default umask P AUTH can be one of the following:'
complete -c ftpd -s '?' -l help -d 'give this help list'
complete -c ftpd -l usage -d 'give a short usage message'
complete -c ftpd -s V -l version -d 'print program version'

