# groups
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/groups.1.gz
complete -c groups -l help -d 'display this help and exit'
complete -c groups -l version -d 'output version information and exit AUTHOR Written by David MacKenzie and Jam…'

