# hostname
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hostname.1.gz
complete -c hostname -s a -l aliases -d 'alias names'
complete -c hostname -s d -l domain -d 'DNS domain name'
complete -c hostname -s f -l fqdn -l long -d 'DNS host name or FQDN'
complete -c hostname -s F -l file -d 'set host name or NIS domain name from FILE'
complete -c hostname -s i -l ip-addresses -d 'addresses for the host name'
complete -c hostname -s s -l short -d 'short host name'
complete -c hostname -s y -l yp -l nis -d 'NIS/YP domain name'
complete -c hostname -s '?' -l help -d 'give this help list'
complete -c hostname -l usage -d 'give a short usage message'
complete -c hostname -s V -l version -d 'print program version'

