# ifconfig
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/ifconfig.8.gz
complete -c ifconfig -s a -d 'display all interfaces which are currently available, even if down'
complete -c ifconfig -s s -d 'display a short list (like netstat -i)'
complete -c ifconfig -s v -d 'be more verbose for some error conditions'

