# inetd
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/inetd.8.gz
complete -c inetd -s d -l debug -d 'turn on debugging, run in foreground mode'
complete -c inetd -l environment -d 'pass local and remote socket information in environment variables'
complete -c inetd -s p -l pidfile -d 'override pidfile (default: "/usr/local/var/run/inetd. pid")'
complete -c inetd -l resolve -d 'resolve IP addresses when setting environment variables (see --environment)'
complete -c inetd -s R -l rate -d 'maximum invocation rate (per minute)'
complete -c inetd -s '?' -l help -d 'give this help list'
complete -c inetd -l usage -d 'give a short usage message'
complete -c inetd -s V -l version -d 'print program version'

