# kill
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/kill.1.gz
complete -c kill -s l -l list -d 'list signal names, or convert signal names to/from numbers'
complete -c kill -s t -l table -d 'print a table of signal information'
complete -c kill -l help -d 'display this help and exit'
complete -c kill -s s -l signal -o SIGNAL -d 'specify the name or number of the signal to be sent'
complete -c kill -l version -d 'output version information and exit'

