# link
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/link.1.gz
complete -c link -l help -d 'display this help and exit'
complete -c link -l version -d 'output version information and exit AUTHOR Written by Michael Stone'

