# llvm-cxxmap
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/llvm-cxxmap.1.gz
complete -c llvm-cxxmap -o remapping-file -s r -d 'Specify a file containing a list of equivalence rules that should be used to …'
complete -c llvm-cxxmap -o output -s o -d 'Specify a file to write the list of matched names to'
complete -c llvm-cxxmap -o Wambiguous -d 'Produce a warning if there are multiple equivalent (but distinct) symbols in …'
complete -c llvm-cxxmap -o Wincomplete -d 'Produce a warning if symbol-file-1 contains a symbol for which there is no eq…'

