# llvm-dis
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/llvm-dis.1.gz
complete -c llvm-dis -s o -d OPTIONS
complete -c llvm-dis -s f -d 'Enable binary output on terminals'
complete -c llvm-dis -o help -d 'Print a summary of command line options'

