# llvm-locstats
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/llvm-locstats.1.gz
complete -c llvm-locstats -l only-variables -d 'calculate the location statistics only for local variables'
complete -c llvm-locstats -l only-formal-parameters -d 'calculate the location statistics only for formal parameters'
complete -c llvm-locstats -l ignore-debug-entry-values -d 'ignore the location statistics on locations containing the debug entry values…'
complete -c llvm-locstats -l draw-plot -d 'make histogram of location buckets generated (requires matplotlib)'
complete -c llvm-locstats -l compare -d 'compare the debug location coverage on two files provided, and draw a plot sh…'

