# llvm-extract
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/llvm-extract.1.gz
complete -c llvm-extract -l alias -d 'Extract the alias named function-name from the LLVM bitcode'
complete -c llvm-extract -l ralias -d 'Extract the alias matching alias-regular-expr from the LLVM bitcode'
complete -c llvm-extract -l bb -d 'Extract basic blocks(s) specified in basic-block-specifier'
complete -c llvm-extract -l delete -d 'Delete specified Globals from Module'
complete -c llvm-extract -s f -d 'Enable binary output on terminals'
complete -c llvm-extract -l func -d 'Extract the function named function-name from the LLVM bitcode'
complete -c llvm-extract -l rfunc -d 'Extract the function(s) matching function-regular-expr from the LLVM bitcode'
complete -c llvm-extract -l glob -d 'Extract the global variable named global-name from the LLVM bitcode'
complete -c llvm-extract -l rglob -d 'Extract the global variable(s) matching global-regular-expr from the LLVM bit…'
complete -c llvm-extract -l keep-const-init -d 'Preserve the values of constant globals'
complete -c llvm-extract -l recursive -d 'Recursively extract all called functions'
complete -c llvm-extract -o help -d 'Print a summary of command line options'
complete -c llvm-extract -s o -d 'Specify the output filename'
complete -c llvm-extract -s S -d 'Write output in LLVM intermediate language (instead of bitcode).  EXIT STATUS'

