# llvm-as
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/llvm-as.1.gz
complete -c llvm-as -s f -d 'Enable binary output on terminals'
complete -c llvm-as -o help -d 'Print a summary of command line options'
complete -c llvm-as -s o -d 'Specify the output file name'

