# llvm-bcanalyzer
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/llvm-bcanalyzer.1.gz
complete -c llvm-bcanalyzer -o nodetails -d 'Causes llvm-bcanalyzer to abbreviate its output by writing out only a module …'
complete -c llvm-bcanalyzer -o dump -d 'Causes llvm-bcanalyzer to dump the bitcode in a human readable format'
complete -c llvm-bcanalyzer -o verify -d 'Causes llvm-bcanalyzer to verify the module produced by reading the bitcode'
complete -c llvm-bcanalyzer -o help -d 'Print a summary of command line options'

