# llvm-libtool-darwin
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/llvm-libtool-darwin.1.gz
complete -c llvm-libtool-darwin -o arch_only -d 'Build a static library only for the specified <architecture> and ignore all o…'
complete -c llvm-libtool-darwin -o color -d 'Use colors in output'
complete -c llvm-libtool-darwin -s D -d 'Use zero for timestamps and UIDs/GIDs.  This is set by default'
complete -c llvm-libtool-darwin -o filelist -d 'Read input file names from <listfile>'
complete -c llvm-libtool-darwin -s h -o help -d 'Show help and usage for this command'
complete -c llvm-libtool-darwin -o help-list -d 'Show help and usage for this command without grouping the options into catego…'
complete -c llvm-libtool-darwin -s l -d 'Searches for the library libx. a in the library search path'
complete -c llvm-libtool-darwin -s L -d 'Adds <dir> to the list of directories in which to search for libraries'
complete -c llvm-libtool-darwin -o no_warning_for_no_symbols -d 'Do not warn about files that have no symbols'
complete -c llvm-libtool-darwin -s o -d 'Specify the output file name.  Must be specified exactly once'
complete -c llvm-libtool-darwin -o static -d 'Produces a static library from the input files'
complete -c llvm-libtool-darwin -s U -d 'Use actual timestamps and UIDs/GIDs'
complete -c llvm-libtool-darwin -s V -d 'Display the version of this program and perform any operation specified'
complete -c llvm-libtool-darwin -o version -d 'Display the version of this program and exit immediately'

