# llvm-profgen
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/llvm-profgen.1.gz
complete -c llvm-profgen -l format -d 'Specify the format of the generated profile'
complete -c llvm-profgen -l show-mmap-events -d 'Print mmap events'
complete -c llvm-profgen -l show-disassembly -d 'Print disassembled code'
complete -c llvm-profgen -l x86-asm-syntax -d 'Specify whether to print assembly code in AT&T syntax (the default) or Intel …'
complete -c llvm-profgen -l perfscript -d 'Path of perf-script trace created by Linux perf tool with script command(the …'
complete -c llvm-profgen -l binary -d 'Path of the input profiled binary files'
complete -c llvm-profgen -l output -d 'Path of the output profile file'

