# llvm-lipo
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/llvm-lipo.1.gz
complete -c llvm-lipo -o help -s h -d 'Display usage information and exit'
complete -c llvm-lipo -o version -d 'Display the version of this program'
complete -c llvm-lipo -o verify_arch -d 'Take a single input file and verify the specified architectures are present i…'
complete -c llvm-lipo -o archs -d 'Take a single input file and display the architectures present in the file'
complete -c llvm-lipo -o info -d 'Take at least one input file and display the descriptions of each file'
complete -c llvm-lipo -o thin -d 'Take a single universal binary input file and the thin flag followed by an ar…'
complete -c llvm-lipo -o create -d 'Take at least one input file and require the output flag to be specified'
complete -c llvm-lipo -o replace -d 'Take a single universal binary input file and require the output flag to be s…'
complete -c llvm-lipo -o segalign -d 'Additional flag that can be specified with create and replace'

