# llvm-link
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/llvm-link.1.gz
complete -c llvm-link -s f -d 'Enable binary output on terminals'
complete -c llvm-link -s o -d 'Specify the output file name'
complete -c llvm-link -s S -d 'Write output in LLVM intermediate language (instead of bitcode)'
complete -c llvm-link -s d -d 'If specified, llvm-link prints a human-readable version of the output bitcode…'
complete -c llvm-link -o help -d 'Print a summary of command line options'
complete -c llvm-link -s v -d 'Verbose mode.   Print information about what llvm-link is doing'

