# llvm-config
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/llvm-config.1.gz
complete -c llvm-config -l version -d 'Print the version number of LLVM'
complete -c llvm-config -o help -d 'Print a summary of llvm-config arguments'
complete -c llvm-config -l prefix -d 'Print the installation prefix for LLVM'
complete -c llvm-config -l src-root -d 'Print the source root from which LLVM was built'
complete -c llvm-config -l obj-root -d 'Print the object root used to build LLVM'
complete -c llvm-config -l bindir -d 'Print the installation directory for LLVM binaries'
complete -c llvm-config -l includedir -d 'Print the installation directory for LLVM headers'
complete -c llvm-config -l libdir -d 'Print the installation directory for LLVM libraries'
complete -c llvm-config -l cxxflags -d 'Print the C++ compiler flags needed to use LLVM headers'
complete -c llvm-config -l ldflags -d 'Print the flags needed to link against LLVM libraries'
complete -c llvm-config -l libs -d 'Print all the libraries needed to link against the specified LLVM components,…'
complete -c llvm-config -l libnames -d 'Similar to --libs, but prints the bare filenames of the libraries without -l …'
complete -c llvm-config -l libfiles -d 'Similar to --libs, but print the full path to each library file'
complete -c llvm-config -l components -d 'Print all valid component names'
complete -c llvm-config -l targets-built -d 'Print the component names for all targets supported by this copy of LLVM'
complete -c llvm-config -l build-mode -d 'Print the build mode used when LLVM was built (e. g'

