# logger
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/logger.1.gz
complete -c logger -s 4 -l ipv4 -d 'use IPv4 for logging to host'
complete -c logger -s 6 -l ipv6 -d 'use IPv6 with a host target'
complete -c logger -s f -l file -d 'log the content of FILE'
complete -c logger -s h -l host -d 'log to HOST instead of to the default \\,/dev/log\\/'
complete -c logger -s i -l id -d 'log the process id with every line'
complete -c logger -s p -l priority -d 'log with priority PRI'
complete -c logger -s s -l stderr -d 'copy the message to stderr'
complete -c logger -s S -l source -d 'set source IP address'
complete -c logger -s t -l tag -d 'prepend every line with TAG'
complete -c logger -s u -l unix -d 'log to UNIX socket SOCK instead of \\,/dev/log\\/'
complete -c logger -s '?' -l help -d 'give this help list'
complete -c logger -l usage -d 'give a short usage message'
complete -c logger -s V -l version -d 'print program version'

