# logname
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/logname.1.gz
complete -c logname -l help -d 'display this help and exit'
complete -c logname -l version -d 'output version information and exit AUTHOR Written by FIXME: unknown'

