# man
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/man.1.gz
complete -c man -s a -d 'Display all matching manual pages'
complete -c man -s C -d 'Use the specified file instead of the default configuration file'
complete -c man -s c -d 'Copy the manual page to the standard output instead of using more 1 to pagina…'
complete -c man -s f -d 'A synonym for whatis 1'
complete -c man -s h -d 'Display only the SYNOPSIS lines of the requested manual pages'
complete -c man -s k -d 'A synonym for apropos 1'
complete -c man -s l -d 'A synonym for mandoc 1.  The name arguments are interpreted as filenames'
complete -c man -s M -d 'Override the list of standard directories which man searches for manual pages'
complete -c man -s m -d 'Augment the list of standard directories which man searches for manual pages'
complete -c man -s S -d 'Only show pages for the specified machine 1 architecture'
complete -c man -s w -d 'List the pathnames of all matching manual pages instead of displaying any of …'

