# mid3iconv
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mid3iconv.1
complete -c mid3iconv -l debug -s d -d 'Print updated tags'
complete -c mid3iconv -l dry-run -s p -d 'Do not actually modify files'
complete -c mid3iconv -l encoding -s e -d 'Convert from this encoding'
complete -c mid3iconv -l force-v1 -d 'Use an ID3v1 tag even if an ID3v2 tag is present'
complete -c mid3iconv -l quiet -s q -d 'Only output errors'
complete -c mid3iconv -l remove-v1 -d 'Remove any ID3v1 tag after processing the files'

