# mid3v2
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mid3v2.1
complete -c mid3v2 -s q -l quiet -d 'Be quiet: do not mention file operations that perform the user\\(aqs request'
complete -c mid3v2 -s v -l verbose -d 'Be verbose: state all operations performed.  This is the opposite of --quiet'
complete -c mid3v2 -s e -l escape -d 'Enable interpretation of backslash escapes for tag values'
complete -c mid3v2 -s f -l list-frames -d 'Display all supported ID3v2. 3/2. 4 frames and their meanings'
complete -c mid3v2 -s L -l list-genres -d 'List all ID3v1 numeric genres'
complete -c mid3v2 -s l -l list -d 'List all tags in the files'
complete -c mid3v2 -l list-raw -d 'List all tags in the files, in raw format'
complete -c mid3v2 -s d -l delete-v2 -d 'Delete ID3v2 tags'
complete -c mid3v2 -s s -l delete-v1 -d 'Delete ID3v1 tags'
complete -c mid3v2 -s D -l delete-all -d 'Delete all ID3 tags'
complete -c mid3v2 -l delete-frames -d 'Delete specific ID3v2 frames (or groups of frames) from the files'
complete -c mid3v2 -s C -l convert -d 'Convert ID3v1 tags to ID3v2 tags'
complete -c mid3v2 -s a -l artist -d 'Set the artist information (TPE1)'
complete -c mid3v2 -s A -l album -d 'Set the album information (TALB)'
complete -c mid3v2 -s t -l song -d 'Set the title information (TIT2)'
complete -c mid3v2 -s c -l comment -d 'Set a comment (COMM)'
complete -c mid3v2 -s p -l picture -d 'Set the attached picture (APIC)'
complete -c mid3v2 -s g -l genre -d 'Set the genre information (TCON)'
complete -c mid3v2 -s y -l year -l date -d 'Set the year/date information (TDRC)'
complete -c mid3v2 -s T -l track -d 'Set the track number (TRCK)'
complete -c mid3v2 -l WXXX -l WXXX

