# mid3cp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mid3cp.1
complete -c mid3cp -l verbose -s v -d 'Be verbose: state all operations performed, and list tags in source file'
complete -c mid3cp -l write-v1 -d 'Write ID3v1 tags to the destination file, derived from the ID3v2 tags'
complete -c mid3cp -l exclude-tag -s x -d 'Exclude a specific tag from being copied.  Can be specified multiple times'
complete -c mid3cp -l merge -d 'Copy over frames instead of replacing the whole ID3 tag'

