# mii-tool
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/mii-tool.8.gz
complete -c mii-tool -s v -l verbose -d 'Display more detailed MII status information'
complete -c mii-tool -s V -l version -d 'Display program version information'
complete -c mii-tool -s R -l reset -d 'Reset the MII to its default configuration'
complete -c mii-tool -s r -l restart -d 'Restart autonegotiation'
complete -c mii-tool -s w -l watch -d 'Watch interface(s) and report changes in link status'
complete -c mii-tool -s l -l log -d 'Used with -w, records link status changes in the system log instead of printi…'
complete -c mii-tool -s F -l force -d 'Disable autonegotiation, and force the MII to either 100baseTx-FD, 100baseTx-…'
complete -c mii-tool -s A -l advertise -d 'Enable and restart autonegotiation, and advertise only the specified media te…'
complete -c mii-tool -s p -l phy -d 'Override the MII address provided by kernel with value addr'

