# mkfs
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/mkfs.minix.8.gz
complete -c mkfs -l check
complete -c mkfs -l namelength
complete -c mkfs -l lock
complete -c mkfs -l badblocks
complete -c mkfs -s 1
complete -c mkfs -s 2
complete -c mkfs -s 3

