# moggsplit
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/moggsplit.1
complete -c moggsplit -l extension -d 'Use the supplied extension when generating new files; the default is ogg'
complete -c moggsplit -l pattern -d 'Use the supplied pattern when generating new files'
complete -c moggsplit -l m3u -d 'Generate an m3u playlist along with the newly generated files'

