# nameif
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/nameif.8.gz
complete -c nameif -s s -d 'argument is given all error messages go to the syslog'
complete -c nameif -s c -d 'argument is given with a file name that file is read instead of /etc/mactab'

