# netstat
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/netstat.8.gz
complete -c netstat -l route -s r -d 'Display the kernel routing tables'
complete -c netstat -l groups -s g -d 'Display multicast group membership information for IPv4 and IPv6'
complete -c netstat -l interfaces -s i -d 'Display a table of all network interfaces'
complete -c netstat -l masquerade -s M -d 'Display a list of masqueraded connections'
complete -c netstat -l statistics -s s -d 'Display summary statistics for each protocol.  OPTIONS'
complete -c netstat -l verbose -s v -d 'Tell the user what is going on by being verbose'
complete -c netstat -l wide -s W -d 'Do not truncate IP addresses by using output as wide as needed'
complete -c netstat -l numeric -s n -d 'Show numerical addresses instead of trying to determine symbolic host, port o…'
complete -c netstat -l numeric-hosts -d 'shows numerical host addresses but does not affect the resolution of port or …'
complete -c netstat -l numeric-ports -d 'shows numerical port numbers but does not affect the resolution of host or us…'
complete -c netstat -l numeric-users -d 'shows numerical user IDs but does not affect the resolution of host or port n…'
complete -c netstat -l protocol -s A -d 'Specifies the address families (perhaps better described as low level protoco…'
complete -c netstat -l inet -s 4
complete -c netstat -l inet6 -s 6
complete -c netstat -l unix -s x
complete -c netstat -l ipx
complete -c netstat -l ax25
complete -c netstat -l netrom
complete -c netstat -l ddp -d and
complete -c netstat -l bluetooth -d options
complete -c netstat -s c -l continuous -d 'This will cause netstat to print the selected information every second contin…'
complete -c netstat -s e -l extend -d 'Display additional information.   Use this option twice for maximum detail'
complete -c netstat -s o -l timers -d 'Include information related to networking timers'
complete -c netstat -s p -l program -d 'Show the PID and name of the program to which each socket belongs'
complete -c netstat -s l -l listening -d 'Show only listening sockets.   (These are omitted by default. )'
complete -c netstat -s a -l all -d 'Show both listening and non-listening sockets.   With the'
complete -c netstat -s F -d 'Print routing information from the FIB.   (This is the default. )'
complete -c netstat -s C -d 'Print routing information from the route cache'

