# nohup
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/nohup.1.gz
complete -c nohup -l help -d 'display this help and exit'
complete -c nohup -l version -d 'output version information and exit'

