# prtstat
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/prtstat.1.gz
complete -c prtstat -s r -l raw -d 'Print the information in raw format'
complete -c prtstat -s V -l version -d 'Show the version information for prtstat .  FILES'

