# rarp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/rarp.8.gz
complete -c rarp -s V -d 'Display the version of RARP in use'
complete -c rarp -s v -d 'Tell the user what is going on by being verbose'
complete -c rarp -s t -d 'When setting or reading the RARP table, this optional parameter tells  rarp w…'
complete -c rarp -l list -d 'Lists the entries in the RARP table'
complete -c rarp -l delete -d 'Remove all RARP entries for the specified host'
complete -c rarp -s a
complete -c rarp -s d
complete -c rarp -s s
complete -c rarp -l set -d 'Create a RARP address mapping entry for host hostname with hardware address s…'

