# route
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/route.8.gz
complete -c route -s A -d 'use the specified address family (eg `inet\')'
complete -c route -s F -d 'operate on the kernel\'s FIB (Forwarding Information Base) routing table'
complete -c route -s C -d 'operate on the kernel\'s routing cache'
complete -c route -s v -d 'select verbose operation'
complete -c route -s n -d 'show numerical addresses instead of trying to determine symbolic host names'
complete -c route -s e -d 'use  netstat (8)-format for displaying the routing table'
complete -c route -o net -d 'the  target is a network'
complete -c route -o host -d 'the  target  is a host'
complete -c route -s 6 -d 'as an alias for '
complete -c route -l inet6 -d 'and '
complete -c route -s 4 -d 'as an alias for '
complete -c route -o ee -d 'will generate a very long line with all parameters from the routing table'

