# telnet
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/telnet.1.gz
complete -c telnet -s 4 -l ipv4 -d 'use only IPv4'
complete -c telnet -s 6 -l ipv6 -d 'use only IPv6'
complete -c telnet -s 8 -l binary -d 'use an 8-bit data transmission'
complete -c telnet -s a -l login -d 'attempt automatic login'
complete -c telnet -s c -l no-rc -d 'do not read the user\'s . telnetrc file'
complete -c telnet -s d -l debug -d 'turn on debugging'
complete -c telnet -s e -l escape -d 'use CHAR as an escape character'
complete -c telnet -s E -l no-escape -d 'use no escape character'
complete -c telnet -s K -l no-login -d 'do not automatically login to the remote system'
complete -c telnet -s l -l user -d 'attempt automatic login as USER'
complete -c telnet -s L -l binary-output -d 'use an 8-bit data transmission for output only'
complete -c telnet -s n -l trace -d 'record trace information into FILE'
complete -c telnet -s r -l rlogin -d 'use a user-interface similar to rlogin'
complete -c telnet -s '?' -l help -d 'give this help list'
complete -c telnet -l usage -d 'give a short usage message'
complete -c telnet -s V -l version -d 'print program version'

