# tftp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/tftp.1.gz
complete -c tftp -s v -l verbose -d 'verbose output'
complete -c tftp -s '?' -l help -d 'give this help list'
complete -c tftp -l usage -d 'give a short usage message'
complete -c tftp -s V -l version -d 'print program version AUTHOR Written by many authors'

