# tftpd
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/tftpd.8.gz
complete -c tftpd -s l -l logging -d 'enable logging'
complete -c tftpd -s n -l nonexistent -d 'supress negative acknowledgement of requests for nonexistent relative filenam…'
complete -c tftpd -s g -l group -d 'set explicit group of process owner, used with \'-s\''
complete -c tftpd -s s -l secure-dir -d 'change root directory to DIR before searching and serving content'
complete -c tftpd -s u -l user -d 'set name of process owner, used with \'-s\' and defaults to \'nobody\''
complete -c tftpd -s '?' -l help -d 'give this help list'
complete -c tftpd -l usage -d 'give a short usage message'
complete -c tftpd -s V -l version -d 'print program version'

