# tsort
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/tsort.1.gz
complete -c tsort -l help -d 'display this help and exit'
complete -c tsort -l version -d 'output version information and exit AUTHOR Written by Mark Kettenis'

