# unbound-control
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/unbound-control.8.gz
complete -c unbound-control -s h -d 'Show the version and commandline option help'
complete -c unbound-control -s c -d 'The config file to read with settings'
complete -c unbound-control -s s -d 'IPv4 or IPv6 address of the server to contact'
complete -c unbound-control -s q -d 'quiet, if the option is given it does not print anything if it works ok'

