# unbound-host
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/unbound-host.1.gz
complete -c unbound-host -s r
complete -c unbound-host -s h -d 'Show the version and commandline option help'
complete -c unbound-host -s v -d 'Enable verbose output and it shows validation results, on every line'
complete -c unbound-host -s d -d 'Enable debug output to stderr'
complete -c unbound-host -s c -d 'Specify the class to lookup for, the default is IN the internet class'
complete -c unbound-host -s t -d 'Specify the type of data to lookup'
complete -c unbound-host -s y -d 'Specify a public key to use as trust anchor'
complete -c unbound-host -s D -d 'Enables DNSSEC validation'
complete -c unbound-host -s f -d 'Reads keys from a file'
complete -c unbound-host -s F -d 'Reads keys from a BIND-style named. conf file'
complete -c unbound-host -s C -d 'Uses the specified unbound. conf to prime libunbound (3)'
complete -c unbound-host -s 4 -d 'Use solely the IPv4 network for sending packets'
complete -c unbound-host -s 6 -d 'Use solely the IPv6 network for sending packets'

