# unzipsfx
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/unzipsfx.1.gz
complete -c unzipsfx -s j -s V -d 'following operating-system specific options:  -X (restore VMS owner/protectio…'

