# yes
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/yes.1.gz
complete -c yes -l help -d 'display this help and exit'
complete -c yes -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

